Load libraries and data

In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [3]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [4]:
path = "C:\\Users\\z3066824\\OneDrive - UNSW\Documents\\"

In [5]:
file = "train.csv"

In [6]:
df = pd.read_csv(path+file)

In [7]:
df

Id  GP   MIN   PTS  FGM  FGA   FG%  3P Made  3PA   3P%  ...  FTA  \
0     10556  80  24.3   7.8  3.0  6.4  45.7      0.1  0.3  22.6  ...  2.9   
1      5342  75  21.8  10.5  4.2  7.9  55.1     -0.3 -1.0  34.9  ...  3.6   
2      5716  85  19.1   4.5  1.9  4.5  42.8      0.4  1.2  34.3  ...  0.6   
3     13790  63  19.1   8.2  3.5  6.7  52.5      0.3  0.8  23.7  ...  1.5   
4      5470  63  17.8   3.7  1.7  3.4  50.8      0.5  1.4  13.7  ...  0.5   
...     ...  ..   ...   ...  ...  ...   ...      ...  ...   ...  ...  ...   
7995   2996  32   9.2   1.8  0.7  1.8  40.3     -0.1 -0.2  23.1  ...  0.6   
7996  11679  54   6.0   1.8  0.7  1.4  48.7      0.1  0.1   3.1  ...  0.4   
7997   5537  85  28.2  10.7  4.0  9.0  45.1      0.2  0.6  23.6  ...  3.9   
7998   1292  39   7.7   2.5  1.0  2.3  40.1     -0.3 -0.5  13.3  ...  0.7   
7999   2900  49  19.2   4.8  1.7  5.1  32.6      0.7  2.4  41.3  ...  1.3   

       FT%  OREB  DREB  REB  AST  STL  BLK  TOV  TARGET_5Yrs  
0     72.1   2.2   2.0  3.8  3.2  1.1  0.2  1.6            1  
1     67.8   3.6   3.7  6.6  0.7  0.5  0.6  1.4            1  
2     75.7   0.6   1.8  2.4  0.8  0.4  0.2  0.6            1  
3     66.9   0.8   2.0  3.0  1.8  0.4  0.1  1.9            1  
4     54.0   2.4   2.7  4.9  0.4  0.4  0.6  0.7            1  
...    ...   ...   ...  ...  ...  ...  ...  ...          ...  
7995  65.7   0.3   1.8  1.9  0.5  0.3  0.2  0.4            1  
7996  70.1   1.0   1.1  2.0  0.1  0.0  0.3  0.3            1  
7997  69.7   1.0   2.1  3.1  3.4  1.2  0.2  1.8            1  
7998  74.3   0.4   0.6  0.9  0.2  0.3  0.3  0.5            1  
7999  70.1   0.1   1.1  1.2  3.5  0.9 -0.3  1.4            1  

[8000 rows x 21 columns]

In [8]:
df.columns

Index(['Id', 'GP', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%', '3P Made', '3PA', '3P%',
       'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV',
       'TARGET_5Yrs'],
      dtype='object')

In [9]:
df.shape

(8000, 21)

In [10]:
df.set_index('Id')

GP   MIN   PTS  FGM  FGA   FG%  3P Made  3PA   3P%  FTM  FTA   FT%  \
Id                                                                          
10556  80  24.3   7.8  3.0  6.4  45.7      0.1  0.3  22.6  2.0  2.9  72.1   
5342   75  21.8  10.5  4.2  7.9  55.1     -0.3 -1.0  34.9  2.4  3.6  67.8   
5716   85  19.1   4.5  1.9  4.5  42.8      0.4  1.2  34.3  0.4  0.6  75.7   
13790  63  19.1   8.2  3.5  6.7  52.5      0.3  0.8  23.7  0.9  1.5  66.9   
5470   63  17.8   3.7  1.7  3.4  50.8      0.5  1.4  13.7  0.2  0.5  54.0   
...    ..   ...   ...  ...  ...   ...      ...  ...   ...  ...  ...   ...   
2996   32   9.2   1.8  0.7  1.8  40.3     -0.1 -0.2  23.1  0.4  0.6  65.7   
11679  54   6.0   1.8  0.7  1.4  48.7      0.1  0.1   3.1  0.2  0.4  70.1   
5537   85  28.2  10.7  4.0  9.0  45.1      0.2  0.6  23.6  2.8  3.9  69.7   
1292   39   7.7   2.5  1.0  2.3  40.1     -0.3 -0.5  13.3  0.6  0.7  74.3   
2900   49  19.2   4.8  1.7  5.1  32.6      0.7  2.4  41.3  0.8  1.3  70.1   

       OREB  DREB  REB  AST  STL  BLK  TOV  TARGET_5Yrs  
Id                                                       
10556   2.2   2.0  3.8  3.2  1.1  0.2  1.6            1  
5342    3.6   3.7  6.6  0.7  0.5  0.6  1.4            1  
5716    0.6   1.8  2.4  0.8  0.4  0.2  0.6            1  
13790   0.8   2.0  3.0  1.8  0.4  0.1  1.9            1  
5470    2.4   2.7  4.9  0.4  0.4  0.6  0.7            1  
...     ...   ...  ...  ...  ...  ...  ...          ...  
2996    0.3   1.8  1.9  0.5  0.3  0.2  0.4            1  
11679   1.0   1.1  2.0  0.1  0.0  0.3  0.3            1  
5537    1.0   2.1  3.1  3.4  1.2  0.2  1.8            1  
1292    0.4   0.6  0.9  0.2  0.3  0.3  0.5            1  
2900    0.1   1.1  1.2  3.5  0.9 -0.3  1.4            1  

[8000 rows x 20 columns]

Define X and y and solit the training and testing data

In [11]:
X = df.iloc[:, 0:20].values
y = df.iloc[:, 20].values

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state = 0)

In [13]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
regressor = RandomForestRegressor(n_estimators = 20, random_state = 0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [15]:
y_pred

array([0.9 , 0.7 , 0.95, ..., 1.  , 0.85, 0.85])

Check the accuracy of the model

In [16]:
print ('Mean Absolute Error:', metrics.mean_absolute_error (y_test, y_pred))

Mean Absolute Error: 0.26670000000000005


In [17]:
print ('Mean Squared Error:', metrics.mean_squared_error (y_test, y_pred))

Mean Squared Error: 0.13858249999999997


In [18]:
print ('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error (y_test, y_pred)))

Root Mean Squared Error: 0.3722667054680018


Determine confusion matrix and accuracy score

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [20]:
r_f = RandomForestRegressor(n_estimators = 1, random_state = 0)

In [21]:
r_f.fit(X_train, y_train)
y_pred2 = r_f.predict(X_test)
y_pred2

array([1., 1., 1., ..., 1., 0., 1.])

In [22]:
print(confusion_matrix(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))

[[  99  235]
 [ 293 1373]]
0.736


Create csv of preditions

In [24]:
pd.DataFrame(y_pred2).to_csv("C:\\Users\\z3066824\\OneDrive - UNSW\Documents\\Blamires_Sean.csv")